/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_drunkeninsomnia_testnative_MyNdk */

#ifndef _Included_com_drunkeninsomnia_testnative_MyNdk
#define _Included_com_drunkeninsomnia_testnative_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_drunkeninsomnia_testnative_MyNdk
 * Method:    FindObject
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_drunkeninsomnia_testnative_MyNdk_FindObject
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
